---
title: "viz_and_eda"
author: "yc4384_Yangyang_Chen"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
```

```{r, cache=TRUE}
pulse_df = 
  haven::read_sas("data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names()
```

```{r}
pulse_tidy_df = 
  pulse_df |> 
  pivot_longer(bdi_score_bl:bdi_score_12m,
               names_to = "visit",
               names_prefix = "bdi_score_",
               values_to = "bdi") |> 
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit)
  )
```

```{r}
litters_wide = 
  read_csv(
    "data/FAS_litters.csv",
    na = c("NA", ".", "")
  ) |> 
  janitor::clean_names() |> 
  select(litter_number, ends_with("weight")) |> 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd",
    values_to = "weight"
  ) |> 
  mutate(
    gd = case_match(
      gd,
      "gd0_weight" ~ 0,
      "gd18_weight" ~ 18
    )
  )
```

```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

analysis_result
```


```{r}
pivot_wider(
  analysis_result, 
  names_from = "time", 
  values_from = "mean") |> 
  knitr::kable()
```

```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")
```

```{r}
lotr_tidy = 
  bind_rows(fellowship_ring, two_towers, return_king) |>
  janitor::clean_names() |>
  pivot_longer(
    female:male,
    names_to = "gender", 
    values_to = "words") |>
  mutate(race = str_to_lower(race)) |> 
  select(movie, everything())

lotr_tidy
```

```{r}
pup_df = 
  read_csv(
    "./data/FAS_pups.csv",
    na = c("NA", "", ".")) |>
  janitor::clean_names() |>
  mutate(
    sex = 
      case_match(
        sex, 
        1 ~ "male", 
        2 ~ "female"),
    sex = as.factor(sex)) 
```

```{r}
pup_df = 
  read_csv(
    "data/FAS_pups.csv",
    na = c("NA", "", ".") 
  ) |> 
  janitor::clean_names() |> 
  mutate(
    sex = 
      case_match(
        sex,
        1 ~ "male",
        2 ~ "female"
      ),
    sex = as.factor(sex)
  )
```

```{r}
litter_df = 
  read_csv(
    "./data/FAS_litters.csv",
    na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  separate(group, into = c("dose", "day_of_tx"), sep = 3) |>
  relocate(litter_number) |>
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    dose = str_to_lower(dose))
```

```{r}
surv_os = 
  read_csv("data/surv_os.csv") |> 
  janitor::clean_names() |> 
  rename(id = what_is_your_uni, os = what_operating_system_do_you_use)
```

```{r}
surv_pr_git = 
  read_csv("data/surv_program_git.csv") |> 
  janitor::clean_names() |> 
  rename(
    id = what_is_your_uni, 
    prog = what_is_your_degree_program,
    git_exp = which_most_accurately_describes_your_experience_with_git)
```

```{r}
left_join(surv_os, surv_pr_git)
inner_join(surv_os, surv_pr_git)
anti_join(surv_os, surv_pr_git)
anti_join(surv_pr_git, surv_os)
```

```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") |>
  janitor::clean_names() |>
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi") |>
  select(id, visit, everything()) |>
  mutate(
    visit = recode(visit, "bl" = "00m"),
    visit = factor(visit, levels = str_c(c("00", "01", "06", "12"), "m"))) |>
  arrange(id, visit)


ggplot(pulse_data, aes(x = visit, y = bdi)) + 
  geom_boxplot()
```


